version: '2'

services: 
    apache:
        image: 'kretakopi:latest'
        restart: always
        volumes: 
            - './site/:/var/www/html'
        ports:
            - '8080:80'
    mariadb:
        image: 'mariadb/server:10.3'
        restart: always
        volumes:
            - './database/:/var/lib/mysql'
        ports:
            - '8082:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=database1
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
            - '8081:80'
        volumes: 
            - './config.inc.php:/etc/phpmyadmin/config.inc.php'

